version: '1.1.{build}'

os: Visual Studio 2017
platform: x64
clone_folder: C:\src
clone_depth: 1
test: off

configuration:
 - Release

build_script:
 - msbuild "C:\src\visual-studio\quake3.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

install:
 - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%

artifacts:
 - path: bin\x64\Release\quake3-ke.exe
   name: 'quake3-ke-$(COMMIT_SHA)'
   
